apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xfjeqi7on-python 
  janus-idp.io/tekton: xfjeqi7on-python
  backstage.io/kubernetes-id: xfjeqi7on-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xfjeqi7on-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml